### ISSUE TITLE
Troubles with initialize_shared_storage and trailing / in link

### ISSUE THREAD

**Issue by ymartin59** [linsomniac/drbdlinks#4]
It took me a while to figure out that the trailing `/` at the end of my directive

```
link('/var/lib/postgresql/')
```

was the reason why `initialize_shared_storage` failed to detect lacking target directories and just aborted its copy tentative.

It would be an interesting improvement to discard trailing slash if present in link declaration or else to abort early with dedicated error message.

**Comment by linsomniac** [comment]
I believe I have this fixed.
